### ISSUE TITLE
CIA Launcher

### ISSUE THREAD

**Issue by Lincoln-LM** [zaksabeast/PokeReader#19]
now that the projects up and running along with the launcher being fully functional, a cia to launch pkrd would be much faster and more convenient

**Comment by zaksabeast** [comment]
Initial launcher cia added in 8c36865f2eea80254f256e1446aace8499a0298c.  Although we need a banner and icon for it to be solid.

**Comment by zaksabeast** [comment]
Closing since Reader is now loaded from [Plug-n-play](https://github.com/zaksabeast/3ds-Plug-n-play) as of 7742eef366ad4e124054afcc1ee13662d547c0bf, and pnp includes a launcher.
