### ISSUE TITLE
SRing causes problems

### ISSUE THREAD

**Issue by Real96** [zaksabeast/PokeReader#41]
User @OPBreloom found out that sring on xyoras, using the old 3ds, the script stops working correctly as showed in the following screen:

![IMG_4135](https://github.com/zaksabeast/PokeReader/assets/20956021/b624ce07-eac5-4567-92b2-3ed152753c67)

**Comment by zaksabeast** [comment]
It looks like this was fixed at some point, probably with the 3gx port.
